env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - google
parserOptions:
  ecmaFeatures:
    jsx: true
  sourceType: module
plugins:
  - react
ignorePatterns:
  - node_modules/**
  - build/**
rules: {
  "require-jsdoc": 0,
  "react/prop-types": 0,
  "comma-dangle": 0,
  "indent": ["error", 2],
  "max-len": 0,
  "arrow-parens": 0
}
