name: CICD
on:
  push:
jobs:
  ci:
    uses: LucasCarioca/workflows/.github/workflows/ci-yarn.yml@v0.10.3
  release:
    if: github.ref == 'refs/heads/main'
    needs: [ci]
    uses: LucasCarioca/workflows/.github/workflows/release-yarn-docker.yml@v0.10.3
    with:
      registry: ghcr.io
      image_name: lucascarioca/wedding-registration-guest
      env_file: prod.env
      build: false
      platforms: linux/amd64
    secrets:
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
