name: CICD
on:
  push:
jobs:
  ci:
    uses: LucasCarioca/workflows/.github/workflows/ci-yarn.yml@v0.1.1
  release:
    needs: ci
    if: github.ref == 'ref/head/main'
    uses: LucasCarioca/workflows/.github/workflows/release-homelab-yarn.yml@v0.1.1
    with:
      registry: ghcr.io
      image_name: lucascarioca/wedding-registration-guest
      deployment: wedding-registration-guest-deployment
      container: wedding-registration-guest
      namespace: wedding
    secrets:
      kube_config: ${{ secrets.HOME_LAB_KUBE_CONFIG }}
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}