name: CICD
on:
  push:
jobs:
  ci:
    uses: LucasCarioca/workflows/.github/workflows/ci-yarn.yml@v0.9.9
 release:
   if: github.ref == 'refs/heads/main'
   needs: [ci]
   uses: LucasCarioca/workflows/.github/workflows/release-yarn-docker.yml@v0.9.9
   with:
     registry: ghcr.io
     image_name: lucascarioca/wedding-registration-guest
     env_file: prod.env
   secrets:
     username: ${{ github.actor }}
     password: ${{ secrets.GITHUB_TOKEN }}
