name: CICD
on:
  workflow_dispatch:
jobs:
  ci:
    uses: LucasCarioca/workflows/.github/workflows/ci-yarn.yml@v0.5.1
  release:
    needs: ci
    uses: LucasCarioca/workflows/.github/workflows/release-homelab-yarn.yml@v0.5.1
    with:
      registry: ghcr.io
      image_name: lucascarioca/wedding-registration-guest
      deployment: wedding-guest
      container: wedding-guest
      namespace: wedding
    secrets:
      kube_config: ${{ secrets.DO_KUBE_CONFIG }}
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}