name: Promote -> DO
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
jobs:
#  release:
#    uses: LucasCarioca/workflows/.github/workflows/release-do-yarn.yml@v0.5.1
#    with:
#      registry: ghcr.io
#      image_name: lucascarioca/wedding-registration-guest
#      deployment: wedding-guest
#      container: wedding-guest
#      namespace: wedding
#    secrets:
#      kube_config: ${{ secrets.DO_KUBE_CONFIG }}
#      username: ${{ github.actor }}
#      password: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    needs: [release, ci]
    uses: LucasCarioca/workflows/.github/workflows/deploy-kubernetes.yml@v0.9.7
    with:
      registry: ghcr.io
      image_name: lucascarioca/wedding-registration-guest
      deployment: wedding-guest
      container: wedding-guest
      namespace: wedding
      version: ${{ needs.release.outputs.version }}
      config_path: k8s/do
    secrets:
      kube_config: ${{ secrets.DO_KUBE_CONFIG }}
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
