name: Promote -> DO
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
env:
  WORKFLOWS_VERSION: v0.9.8
jobs:
  deploy:
    uses: LucasCarioca/workflows/.github/workflows/deploy-kubernetes.yml@@${{ env.WORKFLOWS_VERSION }}
    with:
      registry: ghcr.io
      image_name: lucascarioca/wedding-registration-guest
      deployment: wedding-guest
      container: wedding-guest
      namespace: wedding
      version: ${{ inputs.version }}
      config_path: k8s/do
    secrets:
      kube_config: ${{ secrets.DO_KUBE_CONFIG }}
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
